test:
  uri: lb://service-order
  customerUri: lb://service-customer

# 服务名称
spring:
  application:
    name: service-gateway
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
            - id: route_service_order
              uri: ${test.uri} # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
              predicates:
              - Path=/user/**

            - id: route_service_customer
              uri: ${test.customerUri} # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
              predicates:
              - Path=/customer/**

server:
  port: 5001
# Eureka Server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug