#spring:
#  application:
#    name: gateway-service
#  cloud:        # spring cloud gateway 路由配置方式   ,开启 Gateway 服务注册中心服务发现
#    gateway:
#      discovery:  #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
#        locator:
#          enabled: true     #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
##      routes:
##      - id: 163                     #网关路由到网易官网
##        uri: http://www.163.com/
##        predicates:
##          - Path=/163/**
##      - id: ORDER-SERVICE           #网关路由到订单服务order-service
##        uri: lb://ORDER-SERVICE   #lb开头是使用到了eurake，ws是用到了websocket
##        predicates:
##          - Path=/ORDER-SERVICE/**
##      #- id: wss
##       # uri: lb:ws://ORDER-SERVICE  #websocket形式
##        #predicates:
##         # - Path=/ORDER-SERVICE/**
##      - id: wss1
##        uri: ws://localhost:5100
##        predicates:
##          - Path=/websocket
#server:
#  port: 5001
#
#logging:
#  level:
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: debug
#    org.springframework.web.reactive: debug
#    reactor.ipc.netty: debug
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9797/eureka/
#feign:
#  hystrix:
#    enabled: true
#
#
#

test:
  uri: lb://service-order
  customerUri: lb://service-customer

# 服务名称
spring:
  application:
    name: service-gateway
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
            - id: route_service_order
              uri: ${test.uri} # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
              predicates:
              - Path=/user/**

            - id: route_service_customer
              uri: ${test.customerUri} # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
              predicates:
              - Path=/customer/**

server:
  port: 5001
# Eureka Server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug